import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
// import StairTransition from "@/app/stair";
// import Providers from "@/app/providers";
// import { Debug } from "@/app/components/debug";
import CurveTransition from "@/app/curve";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Providers> */}
        {/* <StairTransition> */}
        <CurveTransition> {children}</CurveTransition>

        {/* </StairTransition> */}
        {/* </Providers> */}
      </body>
    </html>
  );
}
